precision: 'medium'
target_size: &target_size 224
bs: 512
valid_bs: 256
num_workers: 8
patience: 30

image_encoder_args:
  name: 'vit_tiny_patch16_224'
  pretrained: true
  in_chans: 1
  dropout: 0
  metadata: false
  dynamic_img_size: True
  bottleneck_dim: 512

head_args:
  hidden_dim: 256
  bottleneck_dim: 64
  output_dim: 512

optim_args:
  optim: 'adamw'
  lr: 0.0001
  weight_decay: 0.04
  weight_decay_end: 0.4
  warmup_epochs: 10

trainer_args:
  devices: [0]
  precision: '16-mixed'
  min_epochs: 30
  max_epochs: 300
  accumulate_grad_batches: 1
  val_check_interval:
  check_val_every_n_epoch: 1

